baseURL = "https://example.com/"
theme = "hugo-ht"
languageCode = "en-us"
defaultContentLanguage = "cn"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
footnotereturnlinkcontents = "↩"

[module.hugoVersion]
  min = "0.119.0"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = false
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2

[imaging]
  quality = 100

[params]
  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "2.7.5"
  favicon = "media/hugo-logo.png"
  GithubRepo = "https://github.com/USERNAME/REPONAME"
  copyright = "&copy;"
  copyrightYearStart = "2020"
  blogDirName = "posts"
  logo = { url = "hugo-logo.png", width = 50.0, height = 50.0, alt = "Hugo-ht" }

[languages]

  [languages.cn]
    languageName = "中文"
    languageCode = "zh-cn"
    weight = 2
    title = "Hugo-HT"
    contentDir = "content/cn"

    [languages.cn.params]
      description = "你的个人网站"
      licenseURL = "https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans"

    [languages.cn.taxonomies]
      tag = "tags"
      category = "categories"

    [languages.cn.permalinks]
      posts = ":year/:month/:day/:slug/"

    [[languages.cn.menu.main]]
      name = "首页"
      url = "/"
      weight = 1

    [[languages.cn.menu.main]]
      name = "关于"
      url = "/about/"
      weight = 2

    [[languages.cn.menu.main]]
      name = "博客"
      url = "/posts/"
      weight = 3